apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karaoke
  namespace: pomerium
  annotations:
    # Pomerium annotations
    cert-manager.io/issuer: letsencrypt-prod
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"

spec:
  ingressClassName: pomerium
  rules:
  - host: sing.cogo1k.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: karaoke
            port:
              number: 80
  tls:
  - hosts:
    - sing.cogo1k.com
    secretName: sing.cogo1k.com

---
apiVersion: v1
kind: Service
metadata:
  name: karaoke
  namespace: pomerium
spec:
  externalName: karaoke.karaoke.svc.cluster.local
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName